import type { TimezoneCity } from '../types'

export const COMMON_CITIES: TimezoneCity[] = [
  { id: 'pago-pago', name: 'Pago Pago', country: 'American Samoa', continent: 'Oceania', timezoneName: 'Pacific/Pago_Pago' },
  { id: 'honolulu', name: 'Honolulu', country: 'USA', continent: 'Americas', timezoneName: 'Pacific/Honolulu' },
  { id: 'anchorage', name: 'Anchorage', country: 'USA', continent: 'Americas', timezoneName: 'America/Anchorage' },
  { id: 'los-angeles', name: 'Los Angeles', country: 'USA', continent: 'Americas', timezoneName: 'America/Los_Angeles' },
  { id: 'vancouver', name: 'Vancouver', country: 'Canada', continent: 'Americas', timezoneName: 'America/Vancouver' },
  { id: 'denver', name: 'Denver', country: 'USA', continent: 'Americas', timezoneName: 'America/Denver' },
  { id: 'chicago', name: 'Chicago', country: 'USA', continent: 'Americas', timezoneName: 'America/Chicago' },
  { id: 'mexico-city', name: 'Mexico City', country: 'Mexico', continent: 'Americas', timezoneName: 'America/Mexico_City' },
  { id: 'new-york', name: 'New York', country: 'USA', continent: 'Americas', timezoneName: 'America/New_York' },
  { id: 'toronto', name: 'Toronto', country: 'Canada', continent: 'Americas', timezoneName: 'America/Toronto' },
  { id: 'santiago', name: 'Santiago', country: 'Chile', continent: 'Americas', timezoneName: 'America/Santiago' },
  { id: 'buenos-aires', name: 'Buenos Aires', country: 'Argentina', continent: 'Americas', timezoneName: 'America/Argentina/Buenos_Aires' },
  { id: 'sao-paulo', name: 'São Paulo', country: 'Brazil', continent: 'Americas', timezoneName: 'America/Sao_Paulo' },
  { id: 'london', name: 'London', country: 'UK', continent: 'Europe', timezoneName: 'Europe/London' },
  { id: 'paris', name: 'Paris', country: 'France', continent: 'Europe', timezoneName: 'Europe/Paris' },
  { id: 'berlin', name: 'Berlin', country: 'Germany', continent: 'Europe', timezoneName: 'Europe/Berlin' },
  { id: 'rome', name: 'Rome', country: 'Italy', continent: 'Europe', timezoneName: 'Europe/Rome' },
  { id: 'madrid', name: 'Madrid', country: 'Spain', continent: 'Europe', timezoneName: 'Europe/Madrid' },
  { id: 'amsterdam', name: 'Amsterdam', country: 'Netherlands', continent: 'Europe', timezoneName: 'Europe/Amsterdam' },
  { id: 'stockholm', name: 'Stockholm', country: 'Sweden', continent: 'Europe', timezoneName: 'Europe/Stockholm' },
  { id: 'moscow', name: 'Moscow', country: 'Russia', continent: 'Europe', timezoneName: 'Europe/Moscow' },
  { id: 'istanbul', name: 'Istanbul', country: 'Turkey', continent: 'Europe', timezoneName: 'Europe/Istanbul' },
  { id: 'dubai', name: 'Dubai', country: 'UAE', continent: 'Asia', timezoneName: 'Asia/Dubai' },
  { id: 'karachi', name: 'Karachi', country: 'Pakistan', continent: 'Asia', timezoneName: 'Asia/Karachi' },
  { id: 'delhi', name: 'Delhi', country: 'India', continent: 'Asia', timezoneName: 'Asia/Kolkata' },
  { id: 'kolkata', name: 'Kolkata', country: 'India', continent: 'Asia', timezoneName: 'Asia/Kolkata' },
  { id: 'dacca', name: 'Dhaka', country: 'Bangladesh', continent: 'Asia', timezoneName: 'Asia/Dhaka' },
  { id: 'bangkok', name: 'Bangkok', country: 'Thailand', continent: 'Asia', timezoneName: 'Asia/Bangkok' },
  { id: 'jakarta', name: 'Jakarta', country: 'Indonesia', continent: 'Asia', timezoneName: 'Asia/Jakarta' },
  { id: 'beijing', name: 'Beijing', country: 'China', continent: 'Asia', timezoneName: 'Asia/Shanghai' },
  { id: 'shanghai', name: 'Shanghai', country: 'China', continent: 'Asia', timezoneName: 'Asia/Shanghai' },
  { id: 'hong-kong', name: 'Hong Kong', country: 'China', continent: 'Asia', timezoneName: 'Asia/Hong_Kong' },
  { id: 'tokyo', name: 'Tokyo', country: 'Japan', continent: 'Asia', timezoneName: 'Asia/Tokyo' },
  { id: 'seoul', name: 'Seoul', country: 'South Korea', continent: 'Asia', timezoneName: 'Asia/Seoul' },
  { id: 'sydney', name: 'Sydney', country: 'Australia', continent: 'Oceania', timezoneName: 'Australia/Sydney' },
  { id: 'auckland', name: 'Auckland', country: 'New Zealand', continent: 'Oceania', timezoneName: 'Pacific/Auckland' },
  { id: 'cairo', name: 'Cairo', country: 'Egypt', continent: 'Africa', timezoneName: 'Africa/Cairo' },
  { id: 'johannesburg', name: 'Johannesburg', country: 'South Africa', continent: 'Africa', timezoneName: 'Africa/Johannesburg' },
  { id: 'lagos', name: 'Lagos', country: 'Nigeria', continent: 'Africa', timezoneName: 'Africa/Lagos' },
  { id: 'nairobi', name: 'Nairobi', country: 'Kenya', continent: 'Africa', timezoneName: 'Africa/Nairobi' },
]

export const CONTINENTS = ['Americas', 'Europe', 'Asia', 'Africa', 'Oceania'] as const
